command:
  - uvicorn
  - main:app
  - --host
  - 0.0.0.0
  - --port
  - 8080
  - --timeout-keep-alive
  - "120"

env:
  - name: PORT
    value: "8080"
  - name: PYTHONUNBUFFERED
    value: "1"

# Health check configuration for Databricks Apps
health_check:
  path: /healthy
  period_seconds: 30
  timeout_seconds: 10
  failure_threshold: 3

permissions:
  - user_name: users
    level: CAN_USE
